apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    tad.gitops.set/image: ".spec.template.spec.containers[0].image"
    tad.gitops.get/image: ".spec.template.spec.containers[0].image"
    tad.gitops.set/replicas: ".spec.replicas"
    tad.gitops.get/replicas: ".spec.replicas"
  name: backend-tests-python-vmjyleaw
spec:
  replicas: 1
  template:
    spec:
      containers:
        - image: quay.io/tsscui/backend-tests-python-vmjyleaw:dd622c87544710a8ef4a00edf52221ea387f7530@sha256:ea2b5f39bbd97c07d68ad1cf2c08f468ecec324cc7ec1fec202dfea657587902
          name: container-image
